name: Java Continuous Integration with Maven

#Il workflow viene attivato da un evento di push sul ramo master
on:
  push:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      #Eseguire il checkout del repository, Imposta JDK 11 utilizzando l'azione per configurare Java, 
      #specificando la versione 11 e utilizzando la distribuzione di AdoptOpenJDK.
      #Viene utilizzata la cache di Maven per velocizzare le operazioni di compilazione e test.
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
        
    - name: Test case with Maven
      run: mvn -B clean test

  #Fase di compilazione
  build:
    runs-on: ubuntu-latest
    steps:
    #Eseguire il checkout del repository, Imposta JDK 11 utilizzando l'azione per configurare Java, 
    #specificando la versione 11 e utilizzando la distribuzione di AdoptOpenJDK.
    #Viene utilizzata la cache di Maven per velocizzare le operazioni di compilazione e test.
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
  
    - name: Build of Maven
      run: mvn -B package --file pom.xml
